# Generated by Django 2.2 on 2019-05-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='student',
        ),
        migrations.AddField(
            model_name='bus',
            name='student',
            field=models.ManyToManyField(to='driving.Parent'),
        ),
    ]
