# Generated by Django 2.2 on 2019-05-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('secret', models.CharField(max_length=20)),
                ('date_star', models.DateField()),
                ('date_end', models.DateField()),
                ('userType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserType')),
            ],
        ),
    ]
